language: python
node_js: "stable"
cache: pip
python:  3.6

before_install:
  - npm install -g npm@latest

install:
  - npm install -g htmlhint
  - npm install -g jshint
  - npm install -g stylelint
  - pip install pylinkvalidator
  - pip install https://github.com/openwisp/openwisp-utils/tarball/master

script:
  - htmlhint **/*.html *.html --config htmlhint.conf
  - jshint ./js/*.js --config .jshint
  - stylelint "css/*.css" --config .stylelintrc.json
  - python -m http.server 8001 &> /dev/null & pid=$!
  - sleep 5
  - pylinkvalidate.py http://localhost:8001/
  - kill "${pid}"
  - openwisp-utils-qa-checks --skip-checkmigrations --skip-isort --skip-flake8 --skip-checkmakemigrations --skip-checkendline

